# Generated by Django 4.1.6 on 2023-02-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('nid_no', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('present_salary', models.IntegerField()),
                ('expected_salary', models.IntegerField()),
                ('preferred_job', models.CharField(blank=True, max_length=255, null=True)),
                ('carrieer_obj', models.TextField()),
                ('current_degree', models.CharField(max_length=12)),
                ('freelance', models.BooleanField(default=True)),
                ('image1', models.ImageField(upload_to='upload/profile')),
                ('image2', models.ImageField(null=True, upload_to='upload/profile')),
                ('image3', models.ImageField(null=True, upload_to='upload/profile')),
                ('video', models.FileField(null=True, upload_to='upload/video')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_by', models.CharField(max_length=255)),
                ('test_company', models.CharField(max_length=255)),
                ('test_desig', models.CharField(max_length=255)),
                ('testimonial', models.TextField()),
                ('test_image', models.ImageField(blank=True, null=True, upload_to='upload/testimonial')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=255)),
                ('services_desc', models.TextField(max_length=255)),
                ('services_image1', models.ImageField(blank=True, null=True, upload_to='upload/services')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_desc', models.TextField(max_length=255)),
                ('project_cat', models.TextField(max_length=255)),
                ('project_url', models.CharField(max_length=255)),
                ('project_image1', models.ImageField(upload_to='upload/project')),
                ('project_image2', models.ImageField(null=True, upload_to='upload/project')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('duties', models.TextField()),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('cgpa', models.FloatField()),
                ('passing_year', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate', models.FileField(null=True, upload_to='upload/certificate')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
