# Generated by Django 4.1.6 on 2023-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='upload/certificate'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='upload/video'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/project'),
        ),
    ]
